<?php
// GENERATED by `wp mgk gen-layouts`. Do not edit by hand.
return array (
  'home' => 
  array (
    0 => 
    array (
      'id' => '329fc7fc',
      'elType' => 'section',
      'settings' => 
      array (
      ),
      'elements' => 
      array (
        0 => 
        array (
          'id' => 'be1e8573',
          'elType' => 'column',
          'settings' => 
          array (
            '_column_size' => 100,
            '_inline_size' => NULL,
          ),
          'elements' => 
          array (
            0 => 
            array (
              'id' => '52830de9',
              'elType' => 'widget',
              'widgetType' => 'mgk_hero',
              'settings' => 
              array (
              ),
              'elements' => 
              array (
              ),
            ),
          ),
          'isInner' => false,
        ),
      ),
    ),
    1 => 
    array (
      'id' => '0388840d',
      'elType' => 'section',
      'settings' => 
      array (
      ),
      'elements' => 
      array (
        0 => 
        array (
          'id' => 'd530ae53',
          'elType' => 'column',
          'settings' => 
          array (
            '_column_size' => 100,
            '_inline_size' => NULL,
          ),
          'elements' => 
          array (
            0 => 
            array (
              'id' => 'e1dd8f6c',
              'elType' => 'widget',
              'widgetType' => 'mgk_bento',
              'settings' => 
              array (
              ),
              'elements' => 
              array (
              ),
            ),
          ),
          'isInner' => false,
        ),
      ),
    ),
    2 => 
    array (
      'id' => 'fbb2e28d',
      'elType' => 'section',
      'settings' => 
      array (
      ),
      'elements' => 
      array (
        0 => 
        array (
          'id' => 'bd15562f',
          'elType' => 'column',
          'settings' => 
          array (
            '_column_size' => 100,
            '_inline_size' => NULL,
          ),
          'elements' => 
          array (
            0 => 
            array (
              'id' => 'f6955f1e',
              'elType' => 'widget',
              'widgetType' => 'mgk_top_picks',
              'settings' => 
              array (
              ),
              'elements' => 
              array (
              ),
            ),
          ),
          'isInner' => false,
        ),
      ),
    ),
    3 => 
    array (
      'id' => '4a78f8bc',
      'elType' => 'section',
      'settings' => 
      array (
      ),
      'elements' => 
      array (
        0 => 
        array (
          'id' => '8002d80b',
          'elType' => 'column',
          'settings' => 
          array (
            '_column_size' => 100,
            '_inline_size' => NULL,
          ),
          'elements' => 
          array (
            0 => 
            array (
              'id' => 'ce38e0e7',
              'elType' => 'widget',
              'widgetType' => 'mgk_campaign_banner',
              'settings' => 
              array (
              ),
              'elements' => 
              array (
              ),
            ),
          ),
          'isInner' => false,
        ),
      ),
    ),
    4 => 
    array (
      'id' => '1e60c2ac',
      'elType' => 'section',
      'settings' => 
      array (
      ),
      'elements' => 
      array (
        0 => 
        array (
          'id' => 'fc38b396',
          'elType' => 'column',
          'settings' => 
          array (
            '_column_size' => 100,
            '_inline_size' => NULL,
          ),
          'elements' => 
          array (
            0 => 
            array (
              'id' => '4a20b99b',
              'elType' => 'widget',
              'widgetType' => 'mgk_flash_grid',
              'settings' => 
              array (
              ),
              'elements' => 
              array (
              ),
            ),
          ),
          'isInner' => false,
        ),
      ),
    ),
  ),
);
